### ISSUE TITLE
https://youpiny.top/#pricing 无法登录账户

### ISSUE THREAD

**Issue by BruceZhang5337** [GZ1903/v2board_install#5]
您好，我在https://youpiny.top/#pricing购买了VPN服务，发现通过clash for windows延迟一直很大，想登录官网看是否可以换其他途径结果发现没法登录账户，显示500 server error。 此网站说联系您，所以我在此issues 提问。

**Comment by GZ1903** [comment]
？？？？这是一个开源项目，一个一键安装便携使用的工具。无任何实际使用网站。
